#!/usr/bin/env bash
# Bootstrap an Ubuntu EC2 for CareNest (compatible with current AWS Ubuntu images).
# Does not hardcode Python 3.12 — uses the system python3 (e.g. 3.12, 3.13, 3.14).
# Usage: sudo bash deploy/scripts/bootstrap_ec2.sh
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root: sudo bash $0" >&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive

echo "==> Updating apt indexes"
apt-get update -y
apt-get -y upgrade

echo "==> Installing base packages (nginx, build tools, certbot, python3 + venv)"
# Use unversioned python3 / python3-venv so this works on Ubuntu images
# that ship 3.12, 3.13, 3.14, etc. (python3.12 packages are often unavailable).
apt-get -y install \
  nginx git curl ca-certificates gnupg build-essential ufw fail2ban \
  python3 python3-venv python3-pip \
  certbot python3-certbot-nginx rsync

# ---------------------------------------------------------------------------
# Detect / verify Python
# ---------------------------------------------------------------------------
if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: python3 not found after apt install" >&2
  exit 1
fi

PYTHON_BIN="$(command -v python3)"
PYTHON_VER="$("$PYTHON_BIN" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
PYTHON_FULL="$("$PYTHON_BIN" -c 'import sys; print(sys.version.split()[0])')"

echo "==> Detected Python ${PYTHON_FULL} (${PYTHON_BIN})"

# Ensure the venv module works for this interpreter
if ! "$PYTHON_BIN" -c 'import venv' 2>/dev/null; then
  echo "ERROR: python3-venv is missing for ${PYTHON_BIN}" >&2
  echo "Tried package: python3-venv. Install the matching ensurepip/venv package for Python ${PYTHON_VER}." >&2
  exit 1
fi

VENV_SMOKE="/tmp/carenest-venv-smoke-$$"
rm -rf "$VENV_SMOKE"
"$PYTHON_BIN" -m venv "$VENV_SMOKE"
# shellcheck disable=SC1091
source "$VENV_SMOKE/bin/activate"
python -m pip install --upgrade pip >/dev/null
deactivate
rm -rf "$VENV_SMOKE"
echo "==> python3 -m venv OK for Python ${PYTHON_VER}"

# Persist detected interpreter for deploy scripts / operators
mkdir -p /etc/carenest
cat > /etc/carenest/python.env <<EOF
# Generated by bootstrap_ec2.sh — do not hardcode a minor version in deploy scripts
PYTHON_BIN=${PYTHON_BIN}
PYTHON_VERSION=${PYTHON_VER}
EOF
chmod 644 /etc/carenest/python.env

# ---------------------------------------------------------------------------
# Node.js + Yarn
# ---------------------------------------------------------------------------
# Prefer an existing Node (user may already have v22 from Nodesource / snap / nvm).
# Only install Node 22 LTS if missing.
if ! command -v node >/dev/null 2>&1; then
  echo "==> Node not found — installing Node.js 22.x from NodeSource"
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get -y install nodejs
else
  echo "==> Using existing Node $(node -v) at $(command -v node)"
fi

if ! command -v npm >/dev/null 2>&1; then
  echo "ERROR: npm not found (required to install yarn)" >&2
  exit 1
fi

echo "==> Ensuring Yarn Classic (1.22.x)"
install_yarn() {
  # Prefer corepack on Node 16+ when available; fall back to npm global.
  if command -v corepack >/dev/null 2>&1; then
    corepack enable || true
    corepack prepare yarn@1.22.22 --activate && return 0
  fi
  npm install -g yarn@1.22.22
}

if command -v yarn >/dev/null 2>&1; then
  echo "    yarn already present: $(yarn -v) ($(command -v yarn))"
else
  install_yarn
fi

# Verify yarn resolves and runs
if ! command -v yarn >/dev/null 2>&1; then
  echo "ERROR: yarn install failed" >&2
  exit 1
fi
yarn -v >/dev/null
echo "==> Yarn OK: $(yarn -v)"

# ---------------------------------------------------------------------------
# App user + directories
# ---------------------------------------------------------------------------
echo "==> Ensuring carenest user and /opt/carenest layout"
if ! id carenest >/dev/null 2>&1; then
  useradd -m -s /bin/bash carenest
  echo "    created user: carenest"
else
  echo "    user carenest already exists"
fi

mkdir -p \
  /opt/carenest \
  /opt/carenest/app \
  /var/www/carenest/frontend \
  /var/log/carenest \
  /var/backups/carenest

chown -R carenest:carenest /opt/carenest /var/www/carenest /var/log/carenest /var/backups/carenest
chmod 755 /opt/carenest /opt/carenest/app

# Allow carenest to restart its systemd unit without a full root shell (optional; ignore if sudoers missing)
if [[ -d /etc/sudoers.d ]]; then
  cat > /etc/sudoers.d/carenest-api <<'EOF'
carenest ALL=(root) NOPASSWD: /bin/systemctl restart carenest-api, /bin/systemctl status carenest-api, /bin/systemctl reload nginx
EOF
  chmod 440 /etc/sudoers.d/carenest-api
fi

# ---------------------------------------------------------------------------
# Firewall
# ---------------------------------------------------------------------------
echo "==> Configuring UFW"
ufw default deny incoming
ufw default allow outgoing
ufw allow OpenSSH
ufw allow 'Nginx Full'
ufw --force enable

echo
echo "Bootstrap complete."
echo "  Python : ${PYTHON_FULL} (${PYTHON_BIN})  [saved in /etc/carenest/python.env]"
echo "  Node   : $(node -v)"
echo "  Yarn   : $(yarn -v)"
echo "  User   : carenest"
echo "  App dir: /opt/carenest (owned by carenest)"
echo
echo "Next:"
echo "  1) sudo -u carenest git clone <repo> /opt/carenest/app"
echo "     (or: sudo -u carenest git -C /opt/carenest/app pull)"
echo "  2) Configure backend/.env and frontend/.env from deploy/env/"
echo "  3) Install MongoDB or set Atlas MONGO_URL"
echo "  4) Run deploy_backend.sh && deploy_frontend.sh"
echo "  5) Install nginx site + certbot"
