#!/usr/bin/env bash
# Write backend/.env and frontend/.env with correct permissions

_quote_env() {
  # systemd EnvironmentFile + python-dotenv safe double-quoted value
  local s="${1//$'\r'/}"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//$'\n'/\\n}"
  printf '"%s"' "${s}"
}

write_env_files() {
  local backend_env="${APP_ROOT}/backend/.env"
  local frontend_env="${APP_ROOT}/frontend/.env"
  local db_name="${DB_NAME:-carenest}"
  local ses_host="${SES_SMTP_HOST:-email-smtp.ap-south-1.amazonaws.com}"
  local ses_port="${SES_SMTP_PORT:-587}"
  local ses_region="${SES_REGION:-ap-south-1}"
  local email_from="${EMAIL_FROM:-info@${DOMAIN}}"
  local email_from_name="${EMAIL_FROM_NAME:-CareNest Home Health}"
  local lead_notify="${LEAD_NOTIFY_EMAIL:-info@${DOMAIN}}"
  local cors="${CORS_ORIGINS:-https://${DOMAIN},https://${WWW_DOMAIN}}"
  local anthropic_model="${ANTHROPIC_MODEL:-claude-sonnet-4-5-20250929}"

  log "Writing ${backend_env}"
  umask 077
  cat > "${backend_env}" <<EOF
# Generated by deploy/install.sh — do not commit
MONGO_URL=$(_quote_env "${MONGO_URL}")
DB_NAME=$(_quote_env "${db_name}")

ADMIN_TOKEN=$(_quote_env "${ADMIN_TOKEN}")

EMAIL_FROM_NAME=$(_quote_env "${email_from_name}")
EMAIL_FROM=$(_quote_env "${email_from}")
LEAD_NOTIFY_EMAIL=$(_quote_env "${lead_notify}")
SES_REGION=$(_quote_env "${ses_region}")
SES_SMTP_HOST=$(_quote_env "${ses_host}")
SES_SMTP_PORT=$(_quote_env "${ses_port}")
SES_SMTP_USER=$(_quote_env "${SES_SMTP_USER}")
SES_SMTP_PASS=$(_quote_env "${SES_SMTP_PASS}")

ANTHROPIC_API_KEY=$(_quote_env "${ANTHROPIC_API_KEY}")
ANTHROPIC_MODEL=$(_quote_env "${anthropic_model}")

CORS_ORIGINS=$(_quote_env "${cors}")

GA_MEASUREMENT_ID=$(_quote_env "${GA_MEASUREMENT_ID:-}")
GTM_ID=$(_quote_env "${GTM_ID:-}")
META_PIXEL_ID=$(_quote_env "${META_PIXEL_ID:-}")
EOF
  chown "${CARENEST_USER}:${CARENEST_USER}" "${backend_env}"
  chmod 600 "${backend_env}"

  log "Writing ${frontend_env}"
  cat > "${frontend_env}" <<EOF
# Generated by deploy/install.sh — baked at yarn build time
REACT_APP_BACKEND_URL=$(_quote_env "https://${DOMAIN}")
EOF
  chown "${CARENEST_USER}:${CARENEST_USER}" "${frontend_env}"
  chmod 600 "${frontend_env}"

  cat > /etc/carenest/deploy.env <<EOF
DOMAIN=${DOMAIN}
WWW_DOMAIN=${WWW_DOMAIN}
SSL_MODE=${SSL_MODE}
SITE_URL=https://${DOMAIN}
CERTBOT_EMAIL=${CERTBOT_EMAIL}
EOF
  chmod 644 /etc/carenest/deploy.env
}
